# Generated by Django 3.1.7 on 2021-03-28 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(help_text='Name of a US state or territory', max_length=40)),
                ('fips', models.IntegerField(help_text='Assigned fips value (unique identifier)', primary_key=True, serialize=False)),
                ('cases', models.IntegerField(help_text='Number of COVID-19 cases')),
                ('deaths', models.IntegerField(help_text='Number of COVID-19 deaths')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
