# Generated by Django 3.1.7 on 2021-03-28 23:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_county_state_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(help_text='Name of a US state or territory', max_length=40)),
                ('fips', models.IntegerField(help_text='Assigned fips value (unique identifier)', primary_key=True, serialize=False)),
                ('cases', models.IntegerField(help_text='Number of COVID-19 cases')),
                ('deaths', models.IntegerField(help_text='Number of COVID-19 deaths')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['state', 'county_name']},
        ),
        migrations.RemoveField(
            model_name='county',
            name='id',
        ),
        migrations.RemoveField(
            model_name='county',
            name='name',
        ),
        migrations.RemoveField(
            model_name='county',
            name='state_name',
        ),
        migrations.RemoveField(
            model_name='county',
            name='stats',
        ),
        migrations.AddField(
            model_name='county',
            name='cases',
            field=models.IntegerField(default=django.utils.timezone.now, help_text='Number of COVID-19 cases'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='county_and_state',
            field=models.CharField(default='test', help_text='identifier', max_length=90, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='county_name',
            field=models.CharField(default='test', help_text='Name of a US County', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='deaths',
            field=models.IntegerField(default='test2', help_text='Number of COVID-19 cases'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.CharField(default='test3', help_text='Name of the US State that contains it', max_length=40),
            preserve_default=False,
        ),
    ]
