# Generated by Django 3.1.7 on 2021-03-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_name', models.CharField(help_text='Name of a US County', max_length=50)),
                ('state', models.CharField(help_text='Name of the US State that contains it', max_length=40)),
                ('county_and_state', models.CharField(help_text='identifier', max_length=90, primary_key=True, serialize=False)),
                ('cases', models.IntegerField(help_text='Number of COVID-19 cases')),
                ('deaths', models.IntegerField(help_text='Number of COVID-19 cases')),
            ],
            options={
                'ordering': ['state', 'county_name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('name', models.CharField(help_text='Name of a US state or territory', max_length=40)),
                ('fips', models.IntegerField(help_text='Assigned fips value (unique identifier)', primary_key=True, serialize=False)),
                ('cases', models.IntegerField(help_text='Number of COVID-19 cases')),
                ('deaths', models.IntegerField(help_text='Number of COVID-19 deaths')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
