# Generated by Django 3.2 on 2021-04-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['state', 'name']},
        ),
        migrations.RemoveField(
            model_name='county',
            name='county_name',
        ),
        migrations.AddField(
            model_name='county',
            name='name',
            field=models.CharField(default='missing_name', help_text='Name of a US county', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='county',
            name='cases',
            field=models.CharField(help_text='Number of COVID-19 cases', max_length=10),
        ),
        migrations.AlterField(
            model_name='county',
            name='county_and_state',
            field=models.CharField(help_text='Name of county and state - uniquely identifies the county', max_length=90, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='county',
            name='deaths',
            field=models.CharField(help_text='Number of COVID-19 deaths', max_length=10),
        ),
        migrations.AlterField(
            model_name='county',
            name='state',
            field=models.CharField(help_text='Name of a US state or territory', max_length=40),
        ),
    ]
