# Generated by Django 3.2 on 2021-04-26 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210418_1621'),
        ('todo', '0003_userprofile'),
    ]

    operations = [
    ]
