# Generated by Django 3.2 on 2021-04-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_merge_0002_auto_20210418_1621_0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'ordering': ['state', 'county_name']},
        ),
        migrations.RemoveField(
            model_name='county',
            name='name',
        ),
        migrations.AddField(
            model_name='county',
            name='county_name',
            field=models.CharField(default='na', help_text='Name of a US County', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='county',
            name='cases',
            field=models.IntegerField(help_text='Number of COVID-19 cases'),
        ),
        migrations.AlterField(
            model_name='county',
            name='county_and_state',
            field=models.CharField(help_text='identifier', max_length=90, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='county',
            name='deaths',
            field=models.IntegerField(help_text='Number of COVID-19 cases'),
        ),
        migrations.AlterField(
            model_name='county',
            name='state',
            field=models.CharField(help_text='Name of the US State that contains it', max_length=40),
        ),
    ]
