# Generated by Django 3.2 on 2021-04-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210425_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='cases',
            field=models.CharField(help_text='Number of COVID-19 cases', max_length=10),
        ),
        migrations.AlterField(
            model_name='county',
            name='deaths',
            field=models.CharField(help_text='Number of COVID-19 deaths', max_length=10),
        ),
    ]
