# Generated by Django 3.2 on 2021-04-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210425_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='fips',
            field=models.CharField(default='', help_text='Assigned fips value (identifier)', max_length=6),
            preserve_default=False,
        ),
    ]
