# Generated by Django 3.2 on 2021-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_county_fips'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='vuln_score',
            field=models.CharField(default='', help_text='Vulnerability score of the County', max_length=7),
            preserve_default=False,
        ),
    ]
